CREATE EXTENSION postgis;

CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	email VARCHAR NOT NULL
);

CREATE TABLE segments (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	geom GEOGRAPHY(LINESTRING,4326) DEFAULT NULL,
	geom_expanded GEOGRAPHY(POLYGON,4326) DEFAULT NULL
);

CREATE TABLE events (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR NOT NULL
);

CREATE TABLE event_segments (
	event_id BIGINT REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE,
	segment_id BIGINT REFERENCES segments(id) ON UPDATE CASCADE,
	CONSTRAINT event_segments_pkey PRIMARY KEY (event_id, segment_id)
);

CREATE TABLE participations (
	id BIGSERIAL PRIMARY KEY,
	event_id BIGINT REFERENCES events(id),
	user_id BIGINT REFERENCES users(id),
	total_elapsed_seconds DOUBLE PRECISION DEFAULT NULL,
	geom GEOGRAPHY(LINESTRINGZ,4326) DEFAULT NULL
);

CREATE TABLE participation_segments (
	participation_id BIGINT REFERENCES participations(id) ON UPDATE CASCADE ON DELETE CASCADE,
	segment_id BIGINT REFERENCES segments(id) ON UPDATE CASCADE,
	elapsed_seconds DOUBLE PRECISION DEFAULT NULL
);
